### ISSUE TITLE
e-filesDownload: NPE when nothing is downloaded

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#133] opened 2015-02-27 18:22 UTC
Try to "download" this:
<code>file://http://www.opendata.cz/martin/mmr/2015_01-Seznam-prijemcu-(List-of-Beneficiaries)-01_2015.xls</code>
<pre><code>DPU exeution failed!

Stack trace:
eu.unifiedviews.dpu.DPUException DPU.innerExecute throws runtime exception.
   at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:123)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
   at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException null
   ... 4 common frames omitted   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
   at java.lang.Thread.run(Thread.java:745)
</code></pre>

**Comment by eea01** [comment] 2015-03-18 08:11
Mentioned URI contains 2 protocols, FILE and HTTP, which is incorrect. Correct URI examples are in the tool-tip of the URI field. Classes `java.net.URI` nor `org.apache.commons.httpclient.util.URIUtil` are not able to evaluate this URI as invalid, so the DPU discovers during download that it can not find the resource. This is correct resource URI `http://www.opendata.cz/martin/mmr/2015_01-Seznam-prijemcu-(List-of-Beneficiaries)-01_2015.xls` which DPU is able to download. I was not able to reproduce NullPointerException, so could you please add test steps how to reproduce it?

**Comment by eea01** [comment] 2015-04-02 05:45
Please close the issue if there is nothing to do.

**Comment by tomas-knap** [comment] 2015-04-10 07:01
@jakubklimek  Please add the steps to reproduce. 

@eea01 I guess that the filename of the form file://http://xx was created because @jakubklimek basically stored the downloaded http:// resource under the name being equal to the location of the resource.

**Comment by skrchnavy** [comment] 2015-04-21 11:44
@jakubklimek - please provide info/steps to reproduce the issue.

**Comment by mkl-eea-sk** [comment] 2015-07-09 06:59
This is resolved

**Closed by mkl-eea-sk** 2015-07-09 06:59 UTC
Labels: needs discussion, priority: Normal, severity: bug, status: planned

**Comment by skrchnavy** [comment] 2015-07-10 16:49
fixed in merge commit d9f8acdc6462a7ea314bf4383ef4d447039ecb65 so this is fixed for long time
