### ISSUE TITLE
e-filesDownload: DPU ends with Read timed out

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Plugins#229] opened 2015-05-25 12:21 UTC
When uv-e-filesDownload is downloading the file from url: [(http://inspire.geop.sazp.sk/....](http://inspire.geop.sazp.sk/geoserver/wfs?request=GetFeature&version=1.1.0&outputFormat=gml32&typename=lcv:LandCoverUnit&cql_filter="lcv:inspireId/base33:Identifier/base33:namespace" = 'SK:GOV:MOE:SEA:LC') then a user gets an exception down. 

version: uv-e-filesDownload-2.0.1.jar
core:  unifiedviews-backend-2.0.4.jar

How can a user set timeout? There should be the configurable property.

```
2015-05-22 07:19:38,718 [dpu: uv-e-filesDownload] ERROR exec:3 dpu:58 eu.unifiedviews.helpers.dpu.exec.AbstractDpu - DPU exeution failed!
eu.unifiedviews.dpu.DPUException: Exception occured while downloading files.
        at eu.unifiedviews.helpers.dpu.context.ContextUtils.dpuException(ContextUtils.java:193) ~[uv-dpu-helpers-2.0.1.jar:na]
        at eu.unifiedviews.plugins.extractor.filesdownload.FilesDownload.innerExecute(FilesDownload.java:138) ~[na:na]
        at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117) ~[uv-dpu-helpers-2.0.1.jar:na]
        at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232) [backend-2.0.1.jar:na]
        at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370) [backend-2.0.1.jar:na]
        at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452) [backend-2.0.1.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: org.apache.commons.vfs2.FileSystemException: Could not connect to HTTP server on "eunis.eea.europa.eu".
        at org.apache.commons.vfs2.provider.http.HttpClientFactory.createConnection(HttpClientFactory.java:152) ~[na:na]
        at org.apache.commons.vfs2.provider.http.HttpClientFactory.createConnection(HttpClientFactory.java:50) ~[na:na]
        at org.apache.commons.vfs2.provider.http.HttpFileProvider.doCreateFileSystem(HttpFileProvider.java:83) ~[na:na]
        at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.getFileSystem(AbstractOriginatingFileProvider.java:103) ~[na:na]
        at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:81) ~[na:na]
        at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:65) ~[na:na]
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:693) ~[na:na]
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:621) ~[na:na]
        at eu.unifiedviews.plugins.extractor.filesdownload.FilesDownload.innerExecute(FilesDownload.java:135) ~[na:na]
        ... 5 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.7.0_79]
        at java.net.SocketInputStream.read(SocketInputStream.java:152) ~[na:1.7.0_79]
        at java.net.SocketInputStream.read(SocketInputStream.java:122) ~[na:1.7.0_79]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:235) ~[na:1.7.0_79]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:254) ~[na:1.7.0_79]
        at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.vfs2.provider.http.HttpClientFactory.createConnection(HttpClientFactory.java:148) ~[na:na]
        ... 13 common frames omitted
2015-05-22 07:19:38,763 [dpu: uv-e-filesDownload] ERROR exec:3 dpu:58 c.c.mff.xrg.odcs.backend.execution.dpu.DPUExecutor - Execution failed for DPUException.
```

**Comment by jindrichmynarz** [comment] 2015-05-25 12:51
I tested this download using e-filesDownload v1.0.1 and it worked. It indicates that the reported bug is a regression introduced in v2.0.1 of this DPU.

**Comment by skrchnavy** [comment] 2015-06-02 16:39
@Jan-Marcek is this reproducible in released version of UnifiedViews (2.0.2)?

**Comment by Jan-Marcek** [comment] 2015-06-05 09:21
@jindrichmynarz please provide the pipeline which ended with this error.  Is it SAŽP: Corine land cover ? I'm not sure

**Comment by jindrichmynarz** [comment] 2015-06-05 09:39
Yes, it was SAŽP: Corine land cover. See <https://cloud24j.cerit-sc.cz/unifiedviews/#!PipelineEdit/8>.

**Comment by Jan-Marcek** [comment] 2015-06-05 10:22
It still remains. In fact the downloaded url is ```http://inspire.geop.sazp.sk/geoserver/wfs?request=GetFeature&version=1.1.0&outputFormat=gml32&typename=lcv:LandCoverUnit&cql_filter="lcv:inspireId/base33:Identifier/base33:namespace" = 'SK:GOV:MOE:SEA:LC' ``` in takes couple of seconds(minutes?) to download file because server is generating response. If you look close to url you would see that it is kind of query.


Why https://github.com/UnifiedViews/Plugins/blob/develop/e-filesDownload/src/main/java/eu/unifiedviews/plugins/extractor/filesdownload/FilesDownload.java#L93 time out is not configurable?  I know this is develop version and we were using 2.0.1. 

BUT

You can't see any configurable read_timeout in version 2.0.1  https://github.com/UnifiedViews/Plugins/blob/UV_Plugins_v2.0.1/e-filesDownload/src/main/java/eu/unifiedviews/plugins/extractor/filesdownload/FilesDownload.java

**Comment by jindrichmynarz** [comment] 2015-06-05 10:40
Exactly, it is a query to a [WFS](http://en.wikipedia.org/wiki/Web_Feature_Service), which can take a couple of minutes to complete. 

I'm wondering if [this commit](https://github.com/UnifiedViews/Plugins/commit/dc0594135fe8650c4ed90928f51beb7b7296abf1) repairing the time-out settings by @eea01 actually repaired something. I believe that in most cases pipeline creators are OK with long response time, so the default time-out should be fairly long. At the same time, the time-out should be configurable to enable downloading data that takes a long time.

**Comment by mkl-eea-sk** [comment] 2015-06-05 12:53
Just a note, the
https://hc.apache.org/httpclient-3.x/apidocs/org/apache/commons/httpclient/params/HttpConnectionManagerParams.html
is in HttpClients version 3
this class is no longer present in version 4 of HttpClients.
As far as I know, we use HttpClients 4 everywhere... so there must be 
some crazy goings there (either filesDownload uses ver 3 or we set 
parameters to non-used code).

**Comment by mkl-eea-sk** [comment] 2015-06-24 08:01
@mbl-eea-sk  search for apache httpclient 4.x documentation, try to find how to "set read timeout" for tcp connections, then search for apache vfs 2.x documentation and try to find how to pass configuration to underlying filesystem implementation (in this case HTTP). then pass the http read timeout option. do not confuse with "socket timeout" or "connect timeout",  these are different things.

**Comment by mkl-eea-sk** [comment] 2015-06-29 13:13
@jindrichmynarz  this commit https://github.com/UnifiedViews/Plugins/commit/dc0594135fe8650c4ed90928f51beb7b7296abf1 actually sets the timeout to 20 seconds. As far as i understand, you need a field in configuration dialog to set this number to custom value.

@mbl-eea-sk add new text box to configuration dialog with label "Default timeout:" / "
Predvolený časový limit:", add new field to Config class (newest one only): "defaultTimeout", with default value 20000  and link this to vaadin dialog text box. Then, in runtime, fill these values https://github.com/UnifiedViews/Plugins/blob/develop/e-filesDownload/src/main/java/eu/unifiedviews/plugins/extractor/filesdownload/FilesDownload.java#L89-95 with this new property value (accessible using config.getDefaultTimeout())

**Comment by jindrichmynarz** [comment] 2015-07-01 07:50
I installed the DPU from 4967712e8c17388daa98182da7e74e52a3a73868 and there is a problem with migrating configuration from the previous version of the DPU. When I open a pipeline that contains e-filesDownload, the following error is raised:

`Invalid mappings found! Pipeline contained invalid mapping(s). They were removed. List of removed mapping: Edge from uv-e-filesDownload to t-xslt: [filesOutput -> filesInput].`

It seems that the output FilesDataUnit was renamed from `filesOutput` to `output`, which prevents the previous mapping to match. Is this change justified?

When I open the e-filesDownload DPU configuration dialog, the following error is raised:

`Configuration problem
Can't detect configuratino class.`

(Note the typo in "configuratino" instead of "configuration".)

Unfortunately, since I replaced the DPU, cannot find the exact version of this DPU that I had installed previously from which the configuration needs to be migrated (Side question: Is there a log of DPU versions that were installed?).

I'm also unsure if the newly introduced time-out parameter actually works. I used it default setting of 20 seconds and started the pipeline, in which the e-filesDownload DPU started at Jul 1, 2015 9:35:22 AM and finished at Jul 1, 2015 9:40:56 AM (i.e. approximately 5 minutes after). Since the DPU downloads only 1 URL and the time-out is set to 20 seconds, it is strange that its execution takes 5 minutes.

Additionally, the format of the time-out should follow locale. The default value `20,000` milliseconds can be interpreted either as 20 thousand milliseconds in the U.S. locale (interpreting comma as thousands' separator) or 20 milliseconds in the Czech or Slovak locale (interpreting comma as decimal separator).

**Comment by mkl-eea-sk** [comment] 2015-07-01 08:09
@jindrichmynarz @skodape @tomas-knap see this: https://github.com/UnifiedViews/Plugins/issues/204#issuecomment-114820054
here we got it!

@skodape  once again i hope you get @skodape at least @skodape three mail notifications! @skodape 

@tomas-knap you too! :)

@jindrichmynarz as you can see from https://github.com/UnifiedViews/Plugins/commit/4967712e8c17388daa98182da7e74e52a3a73868 we were not changing the name data unit. this happened here https://github.com/UnifiedViews/Plugins/commit/fcac7475bb9d6ed4f926eb6e77f1c5dbd0839273#diff-21384e9264e18d813763c4260c86a27eR56 

@jindrichmynarz pipeline running time - issue of Core. I will give a precise test to parameter on http protocol and inform you.

@jindrichmynarz locale: https://github.com/UnifiedViews/Plugins/commit/4967712e8c17388daa98182da7e74e52a3a73868#diff-12bb9b7ae760a64b4ab16dac53ff1c39R114
I set the text box with locale from UV/Core properties. "20,000" is what Vaadin things, US number should look like. For slovak locale I see "20 000". So this is feature. If you do not want to set locale programmatically, Vaadin chooses one from Accept-Language http header, so, in your case, you get US again (as we found out your browser was set this way last time we debated locale in components)

**Comment by mkl-eea-sk** [comment] 2015-07-01 08:19
@jindrichmynarz I have tested using netcat, timeout values from 10ms (immediate pipeline fail) to 60 seconds and I can confirm, that parameter works. At least for HTTP connections (where it was requested at first place). The running time of pipeline is +- 1 second around timeout, so your pipeline is strange and can inverstigate (if you grant me access to logs)

**Comment by mkl-eea-sk** [comment] 2015-07-01 08:27
Closing - timeout works, locale works. Configuration and data unit rename is something that 'just happened' and has nothing to do with this issue (we can discuss using other channels)

**Closed by mkl-eea-sk** 2015-07-01 08:27 UTC
Labels: priority: Urgent, resolution: fixed, severity: bug, status: resolved
