### ISSUE TITLE
t-xslt: Executing tests failed

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#140] opened 2015-03-09 13:42 UTC
in develop branch (8b2e1d1201f3d0f6dcc8eb6534f63012da813a99), there was a problem with jenkins build - t-xslt DPU - tests for t-xslt, see below:

http://ci.in.eea.sk/view/OpenData.sk/job/UnifiedViews-Plugins%20%28develop%29/55/console

[INFO] ------------------------------------------------------------------------
[INFO] Building T-Xslt 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ t-xslt ---
[INFO] Deleting /home/jenkins/workspace/UnifiedViews-Plugins (develop)/t-xslt/target
[INFO] 
[INFO] --- git-commit-id-plugin:2.1.12:revision (default) @ t-xslt ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ t-xslt ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ t-xslt ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /home/jenkins/workspace/UnifiedViews-Plugins (develop)/t-xslt/target/classes
[WARNING] /home/jenkins/workspace/UnifiedViews-Plugins (develop)/t-xslt/src/main/java/cz/cuni/mff/xrg/uv/transformer/xslt/XsltExecutor.java:[181,32] Serializer(java.io.File) in net.sf.saxon.s9api.Serializer has been deprecated
[WARNING] /home/jenkins/workspace/UnifiedViews-Plugins (develop)/t-xslt/src/main/java/cz/cuni/mff/xrg/uv/transformer/xslt/Xslt.java:[204,55] getFirst(eu.unifiedviews.dataunit.MetadataDataUnit,java.lang.String,java.lang.String) in eu.unifiedviews.helpers.dataunit.metadata.MetadataUtils has been deprecated
[WARNING] /home/jenkins/workspace/UnifiedViews-Plugins (develop)/t-xslt/src/main/java/cz/cuni/mff/xrg/uv/transformer/xslt/Xslt.java:[223,34] set(eu.unifiedviews.dataunit.WritableMetadataDataUnit,java.lang.String,java.lang.String,java.lang.String) in eu.unifiedviews.helpers.dataunit.metadata.MetadataUtils has been deprecated
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ t-xslt ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 10 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ t-xslt ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/jenkins/workspace/UnifiedViews-Plugins (develop)/t-xslt/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ t-xslt ---
[INFO] Surefire report directory: /home/jenkins/workspace/UnifiedViews-Plugins (develop)/t-xslt/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running eu.unifiedviews.plugins.transformer.xslt.XsltTest
07:55:56.932 [main] INFO  c.c.m.x.o.dpu.test.TestEnvironment - Creating cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment with workingDirectory /tmp/5717042575623003313
07:55:56.963 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Initializing NativeStore...
07:55:56.974 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Data dir is /tmp/5717042575623003313/dataUnits/test_env_13576596
07:55:56.994 [main] DEBUG o.openrdf.sail.nativerdf.TripleStore - No indexes specified, using default indexes: spoc,posc
07:55:57.000 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - NativeStore initialized
07:55:57.045 [main] DEBUG o.o.query.parser.QueryParserRegistry - Registered service class org.openrdf.query.parser.serql.SeRQLParserFactory
07:55:57.052 [main] DEBUG o.o.query.parser.QueryParserRegistry - Registered service class org.openrdf.query.parser.sparql.SPARQLParserFactory
07:55:57.201 [main] INFO  c.c.m.x.o.dpu.test.TestEnvironment - Creating cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment with workingDirectory /tmp/3821744911547398446
07:55:57.202 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Initializing NativeStore...
07:55:57.202 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Data dir is /tmp/3821744911547398446/dataUnits/test_env_16477758
07:55:57.204 [main] DEBUG o.openrdf.sail.nativerdf.TripleStore - No indexes specified, using default indexes: spoc,posc
07:55:57.205 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - NativeStore initialized
07:55:57.214 [main] INFO  c.c.m.x.o.dpu.test.TestEnvironment - Creating cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment with workingDirectory /tmp/4347429295662176686
07:55:57.215 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Initializing NativeStore...
07:55:57.215 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Data dir is /tmp/4347429295662176686/dataUnits/test_env_8827511
07:55:57.218 [main] DEBUG o.openrdf.sail.nativerdf.TripleStore - No indexes specified, using default indexes: spoc,posc
07:55:57.218 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - NativeStore initialized
07:55:57.227 [main] INFO  c.c.m.x.o.dpu.test.TestEnvironment - Creating cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment with workingDirectory /tmp/6673793056962807553
07:55:57.227 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Initializing NativeStore...
07:55:57.228 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Data dir is /tmp/6673793056962807553/dataUnits/test_env_29802489
07:55:57.230 [main] DEBUG o.openrdf.sail.nativerdf.TripleStore - No indexes specified, using default indexes: spoc,posc
07:55:57.231 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - NativeStore initialized
07:55:57.239 [main] INFO  c.c.m.x.o.dpu.test.TestEnvironment - Creating cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment with workingDirectory /tmp/1409343320077873474
07:55:57.240 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Initializing NativeStore...
07:55:57.240 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Data dir is /tmp/1409343320077873474/dataUnits/test_env_18311339
07:55:57.243 [main] DEBUG o.openrdf.sail.nativerdf.TripleStore - No indexes specified, using default indexes: spoc,posc
07:55:57.244 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - NativeStore initialized
07:55:57.252 [main] INFO  c.c.m.x.o.dpu.test.TestEnvironment - Creating cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment with workingDirectory /tmp/8333068239194454788
07:55:57.253 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Initializing NativeStore...
07:55:57.253 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Data dir is /tmp/8333068239194454788/dataUnits/test_env_12290617
07:55:57.256 [main] DEBUG o.openrdf.sail.nativerdf.TripleStore - No indexes specified, using default indexes: spoc,posc
07:55:57.256 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - NativeStore initialized
07:55:57.265 [main] INFO  c.c.m.x.o.dpu.test.TestEnvironment - Creating cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment with workingDirectory /tmp/850105690371048677
07:55:57.265 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Initializing NativeStore...
07:55:57.266 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Data dir is /tmp/850105690371048677/dataUnits/test_env_32734484
07:55:57.268 [main] DEBUG o.openrdf.sail.nativerdf.TripleStore - No indexes specified, using default indexes: spoc,posc
07:55:57.269 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - NativeStore initialized
Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.701 sec <<< FAILURE! - in eu.unifiedviews.plugins.transformer.xslt.XsltTest
checkCorrectOutputFileExtension(eu.unifiedviews.plugins.transformer.xslt.XsltTest)  Time elapsed: 0.492 sec  <<< ERROR!
eu.unifiedviews.dataunit.DataUnitException: File does not exist: file:/home/jenkins/workspace/UnifiedViews-Plugins%2520(develop)/t-xslt/target/test-classes/valid-for-xslt.xml. File must exists prior being added.
	at eu.unifiedviews.dataunit.files.impl.LocalFSFilesDataUnit.addExistingFile(LocalFSFilesDataUnit.java:114)
	at eu.unifiedviews.helpers.dataunit.files.FilesDataUnitUtils.addFile(FilesDataUnitUtils.java:73)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.addFileToInput(XsltTest.java:200)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.checkCorrectOutputFileExtension(XsltTest.java:135)

throwExceptionWhenInvalidTemplateSpecified(eu.unifiedviews.plugins.transformer.xslt.XsltTest)  Time elapsed: 0.013 sec  <<< ERROR!
eu.unifiedviews.dataunit.DataUnitException: File does not exist: file:/home/jenkins/workspace/UnifiedViews-Plugins%2520(develop)/t-xslt/target/test-classes/valid.xml. File must exists prior being added.
	at eu.unifiedviews.dataunit.files.impl.LocalFSFilesDataUnit.addExistingFile(LocalFSFilesDataUnit.java:114)
	at eu.unifiedviews.helpers.dataunit.files.FilesDataUnitUtils.addFile(FilesDataUnitUtils.java:73)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.addFileToInput(XsltTest.java:200)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.throwExceptionWhenInvalidTemplateSpecified(XsltTest.java:78)

throwExceptionWhenNonValidXmlIsSpecified(eu.unifiedviews.plugins.transformer.xslt.XsltTest)  Time elapsed: 0.012 sec  <<< ERROR!
eu.unifiedviews.dataunit.DataUnitException: File does not exist: file:/home/jenkins/workspace/UnifiedViews-Plugins%2520(develop)/t-xslt/target/test-classes/not-well-formed.xml. File must exists prior being added.
	at eu.unifiedviews.dataunit.files.impl.LocalFSFilesDataUnit.addExistingFile(LocalFSFilesDataUnit.java:114)
	at eu.unifiedviews.helpers.dataunit.files.FilesDataUnitUtils.addFile(FilesDataUnitUtils.java:73)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.addFileToInput(XsltTest.java:200)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.throwExceptionWhenNonValidXmlIsSpecified(XsltTest.java:106)

checkTemplateVersion2IsSupported(eu.unifiedviews.plugins.transformer.xslt.XsltTest)  Time elapsed: 0.012 sec  <<< ERROR!
eu.unifiedviews.dataunit.DataUnitException: File does not exist: file:/home/jenkins/workspace/UnifiedViews-Plugins%2520(develop)/t-xslt/target/test-classes/document-for-template-version-2.xml. File must exists prior being added.
	at eu.unifiedviews.dataunit.files.impl.LocalFSFilesDataUnit.addExistingFile(LocalFSFilesDataUnit.java:114)
	at eu.unifiedviews.helpers.dataunit.files.FilesDataUnitUtils.addFile(FilesDataUnitUtils.java:73)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.addFileToInput(XsltTest.java:200)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.checkTemplateVersion2IsSupported(XsltTest.java:122)

passForValidXmlAndTemplate(eu.unifiedviews.plugins.transformer.xslt.XsltTest)  Time elapsed: 0.013 sec  <<< ERROR!
eu.unifiedviews.dataunit.DataUnitException: File does not exist: file:/home/jenkins/workspace/UnifiedViews-Plugins%2520(develop)/t-xslt/target/test-classes/valid-for-xslt.xml. File must exists prior being added.
	at eu.unifiedviews.dataunit.files.impl.LocalFSFilesDataUnit.addExistingFile(LocalFSFilesDataUnit.java:114)
	at eu.unifiedviews.helpers.dataunit.files.FilesDataUnitUtils.addFile(FilesDataUnitUtils.java:73)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.addFileToInput(XsltTest.java:200)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.passForValidXmlAndTemplate(XsltTest.java:65)

throwExceptionWhenNoTemplateIsSpecified(eu.unifiedviews.plugins.transformer.xslt.XsltTest)  Time elapsed: 0.013 sec  <<< ERROR!
eu.unifiedviews.dataunit.DataUnitException: File does not exist: file:/home/jenkins/workspace/UnifiedViews-Plugins%2520(develop)/t-xslt/target/test-classes/valid.xml. File must exists prior being added.
	at eu.unifiedviews.dataunit.files.impl.LocalFSFilesDataUnit.addExistingFile(LocalFSFilesDataUnit.java:114)
	at eu.unifiedviews.helpers.dataunit.files.FilesDataUnitUtils.addFile(FilesDataUnitUtils.java:73)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.addFileToInput(XsltTest.java:200)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.throwExceptionWhenNoTemplateIsSpecified(XsltTest.java:94)

checkParamsFromMapAreInOutput(eu.unifiedviews.plugins.transformer.xslt.XsltTest)  Time elapsed: 0.015 sec  <<< ERROR!
eu.unifiedviews.dataunit.DataUnitException: File does not exist: file:/home/jenkins/workspace/UnifiedViews-Plugins%2520(develop)/t-xslt/target/test-classes/valid.xml. File must exists prior being added.
	at eu.unifiedviews.dataunit.files.impl.LocalFSFilesDataUnit.addExistingFile(LocalFSFilesDataUnit.java:114)
	at eu.unifiedviews.helpers.dataunit.files.FilesDataUnitUtils.addFile(FilesDataUnitUtils.java:73)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.addFileToInput(XsltTest.java:200)
	at eu.unifiedviews.plugins.transformer.xslt.XsltTest.checkParamsFromMapAreInOutput(XsltTest.java:156)

Results :

Tests in error: 
  XsltTest.checkCorrectOutputFileExtension:135->addFileToInput:200 » DataUnit Fi...
  XsltTest.checkParamsFromMapAreInOutput:156->addFileToInput:200 » DataUnit File...
  XsltTest.checkTemplateVersion2IsSupported:122->addFileToInput:200 » DataUnit F...
  XsltTest.passForValidXmlAndTemplate:65->addFileToInput:200 » DataUnit File doe...
  XsltTest.throwExceptionWhenInvalidTemplateSpecified:78->addFileToInput:200 » DataUnit
  XsltTest.throwExceptionWhenNoTemplateIsSpecified:94->addFileToInput:200 » DataUnit
  XsltTest.throwExceptionWhenNonValidXmlIsSpecified:106->addFileToInput:200 » DataUnit

Tests run: 7, Failures: 0, Errors: 7, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] E-FilesDownload ................................... SUCCESS [48.905s]
[INFO] E-FilesFromLocal .................................. SUCCESS [12.245s]
[INFO] E-RdfFromSparqlEndpoint ........................... SUCCESS [16.442s]
[INFO] E-HttpDownload .................................... SUCCESS [11.392s]
[INFO] E-UploadToFiles ................................... SUCCESS [11.875s]
[INFO] E-RelationalFromSql ............................... SUCCESS [15.302s]
[INFO] T-SPARQL .......................................... SUCCESS [13.170s]
[INFO] T-SparqlSelect .................................... SUCCESS [11.386s]
[INFO] T-Xslt ............................................ FAILURE [1.842s]
[INFO] T-FilesRenamer .................................... SKIPPED

**Comment by jindrichmynarz** [comment] 2015-03-13 11:59
Running the tests (via `mvn test`) for the t-xslt DPU (develop branch, commit 4d2b96af49564ecdf58345cfd927fde7f0e85661) passes on OS X 10.9.5.

**Comment by skodape** [comment] 2015-03-13 12:00
Works fine on my machine, also the paths looks to be ok. Files are presented in the resources on git-hub: https://github.com/UnifiedViews/Plugins/tree/master/t-xslt/src/test/resources

I do not know what else to check without access to the files on Jenkinse.

**Comment by hanecak** [comment] 2015-03-13 14:40
Works for me too:

Results :

Tests run: 7, Failures: 0, Errors: 0, Skipped: 0

$ java -version
openjdk version "1.8.0_31"
OpenJDK Runtime Environment (build 1.8.0_31-b13)
OpenJDK 64-Bit Server VM (build 25.31-b07, mixed mode)
$ lsb_release -sir
Fedora 20

Jenkins should be investigated instead.

**Comment by eea01** [comment] 2015-03-18 07:48
[This](https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-helpers/src/main/java/eu/unifiedviews/helpers/dpu/test/resources/ResourceUtils.java#L27) could be improved and then engaged in DPUs.

**Comment by skodape** [comment] 2015-03-18 10:02
It might be a good follow up to fix this in helpers ( original call: ResourceUtils.getFile(filename); ).
As now this call is only replaced with functional version on Jenkinse.

For example I do not know and for sure I will not remember to use File(.toURI) .. so next time I may again cause problem with Jenkinse. But if the helpers do the job right for me, then I get it right next time.

**Comment by hanecak** [comment] 2015-03-18 11:42
Please, do not update Helpers or any other code, fix such stuff on "per incident basis" instead (i.e. next time something similar pops up). Why:

Fix, as found in 4f0dbec (line 107) seems not very "intuitive" (as confirmed also by @skodape ). Plus it might indicate that we have some threading issues there somewhere. Thus, I would as of now consider this as "sort of work around", not a true fix for true underlying cause. And because of that, I would like to *not* propagate it further in the code.

As of now, build works:

[INFO] T-Xslt ............................................ SUCCESS [8.680s]

(build #61, http://ci.in.eea.sk/view/OpenData.sk/job/UnifiedViews-Plugins%20%28develop%29/61/console)

so I'm closing this.

**Comment by skodape** [comment] 2015-03-18 11:46
@hanecak just a note: in that case I would expect comment in test that explains why this approach (File(toURI)) is used instead of helpers. 

As otherwise a developer that does not know about this issue may try to reuse code (helpers) and cause Jenkinse build failure - same as happen with DevEnv not so long ago.

**Comment by mkl-eea-sk** [comment] 2015-03-18 12:12
Problem is not in toURI or URL or whatever.
Problem is in classloaders. You cannot use helper's classloader to load resource from DPU's jar. Thats all.
This helper cannot be fixed anyway. Use ordinary this.getClass().getClassloader().getResourceAsStream in your DPU JUnit tests as ordinary. Don't try to write Helper to every two lines of code which occure more than once in source codes...

**Comment by mkl-eea-sk** [comment] 2015-03-18 12:32
Since the classloaders somehow magically works in this case, the real problem is this:
http://stackoverflow.com/questions/8928661/how-to-avoid-getting-url-encoded-paths-from-url-getfile

**Comment by mkl-eea-sk** [comment] 2015-03-18 12:41
as classLoader.getResource().toUri() produces correct URI:
file:/home/jenkins/workspace/UnifiedViews-Plugins%20(develop)/t-xslt/target/test-classes/valid-for-xslt.xml
and classLoader.getResource().getFile() produces
file:/home/jenkins/workspace/UnifiedViews-Plugins%2520(develop)/t-xslt/target/test-classes/valid-for-xslt.xml

But since resource is URL, the getFile() method is for extracting the Path part of URL (with query - the part after ? in URL). It is intended for work with URLs (extracting the path after schema and hostname). So obviously, it returns URL encoded String, which, given to 
new File(String) constructor
simply could not work.
new File(String) expects correct file path, not "path part of URL".

So eea01 made correct fixes:
classloader.getResource().getFile().toURI()
which returns URI instance and then he added usage of
new File(URI)
constructor, which expects URI (which can be URL encoded).

However, working with resources this way is completely wrong in Unit tests. Read first answer here: http://stackoverflow.com/questions/14089146/file-loading-by-getclass-getresource

Always use getResourceAsStream() where you can. If you definitely need files in you unit tests, create new by using File.createTempFile and put desired contents from your resources there, use the file and delete it after executing unit tests.

**Comment by mkl-eea-sk** [comment] 2015-03-18 12:42
Just to notify people

**Closed by mkl-eea-sk** 2015-03-18 12:42 UTC
Labels: priority: Urgent, resolution: fixed, severity: bug, status: resolved
