### ISSUE TITLE
l-rdfToVirtuoso: incorrect treatment of RDF language tags

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#283] opened 2015-07-24 12:06 UTC
Let's say I have an RDF triple with a literal object that specifies a language tag:

```
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

[] skos:prefLabel "Something"@en .
```

When I load this RDF via l-rdfToVirtuoso and then look at it in Virtuoso, it looks like this:

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

[] skos:prefLabel "Something"^^rdf:langString .
```

In other words, the language tag (`en`) is lost and instead replaced by the `rdf:langString` datatype.

When I load the same file directly via Virtuoso upload or via l-filesToVirtuoso, then the language tag is preserved. This is why I assume there is a bug in l-rdfToVirtuoso.

Context: ODN 1.1.0.

**Comment by mkl-eea-sk** [comment] 2015-07-24 13:03
I suspect this
https://github.com/openlink/virtuoso-opensource/blob/develop/7/binsrc/sesame2/virtuoso_driver/VirtuosoRepositoryConnection.java#L2383
to be the cause of bug.
We can see:
```
if (lit.getDatatype() != null)
          {
             ps.setString(4, lit.getDatatype().toString());
             ps.setInt(5, 3);
           }
           else if (lit.getLanguage() != null)
           {
             ps.setString(4, lit.getLanguage());
             ps.setInt(5, 2);
           }
```
which, I think, each lit has datatype in Sesame 2.8.x and this driver 
simply is not patched.
This if never pass to its else if branch (with language).
Even literal with language has its datatype as XSD.String in Sesame i think.

Debugging shows that I am right and the problem is, that in Sesame 2.8.x 
every literal has datatype (in this case it is
XSD.langString). So the if mentioned never branches into its language 
setting branch.

I will try to formulate this and repost to Virtuoso team to fix Sesame 
driver.

**Comment by jindrichmynarz** [comment] 2015-07-24 13:22
Thanks for the thorough analysis. I think it would be best if you can formulate directly what the problem with the Virtuoso's Sesame driver. Providing a patch via pull request might be even better.

**Comment by mkl-eea-sk** [comment] 2015-07-27 07:27
blocked by https://github.com/openlink/virtuoso-opensource/issues/448

**Comment by mkl-eea-sk** [comment] 2015-07-27 07:27
@jindrichmynarz if absolutely necessary, I can provide you with driver.jar where the fix is included

**Comment by jindrichmynarz** [comment] 2015-07-27 07:40
No problem. In the meantime, I can use l-filesToVirtuoso instead.

**Comment by pkleef** [comment] 2015-07-27 14:57
We pushed a fix into the https://github.com/openlink/virtuoso-opensource/commits/develop/7 branch that fixes this problem for both the jena2 and sesame2 providers. The providers have been rebuild with this fix.

**Comment by jindrichmynarz** [comment] 2015-07-27 15:12
Patrick, thank you for a quick response!

@mkl-eea-sk: Is it possible to bump the version of the Virtuoso driver used by l-rdfToVirtuoso, so that we can close this issue?

**Comment by erikap** [comment] 2015-08-05 10:28
I've tested the new version of l-rdfToVirtuoso and it works.
Thanks for the quick fix!

**Closed** 2015-08-05 11:33 UTC
Labels: priority: High, severity: bug, status: approved
