### ISSUE TITLE
E-sparqlEndpoint: Problem when DPU is executed, no class definition found exception during runtime

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#367] opened 2015-11-18 10:20 UTC
When 

Steps: 
1. place e-sparqlEndpoint on the pipeline.
2. Configure it to run agains dbpedia: http://dbpedia.org/sparql, CONSTRUCT { <http://dbpedia.org/resource/Prague> ?p ?o } WHERE { <http://dbpedia.org/resource/Prague> ?p ?o } 
3. Run the pipeline

As a result, error occurs: 

```
org/apache/http/impl/conn/PoolingClientConnectionManagerjava.lang.NoClassDefFoundError: org/apache/http/impl/conn/PoolingClientConnectionManager
at org.apache.http.impl.client.SystemDefaultHttpClient.createClientConnectionManager(SystemDefaultHttpClient.java:121)
at org.apache.http.impl.client.AbstractHttpClient.getConnectionManager(AbstractHttpClient.java:484)
at org.apache.http.impl.client.AbstractHttpClient.close(AbstractHttpClient.java:1011)
at org.apache.http.client.utils.HttpClientUtils.closeQuietly(HttpClientUtils.java:142)
at org.openrdf.http.client.SesameClientImpl.shutDown(SesameClientImpl.java:92)
at org.openrdf.repository.sparql.SPARQLRepository.shutDownInternal(SPARQLRepository.java:182)
at org.openrdf.repository.base.RepositoryBase.shutDown(RepositoryBase.java:52)
at eu.unifiedviews.plugins.extractor.sparqlendpoint.RemoteRdfDataUnit.close(RemoteRdfDataUnit.java:107)
at eu.unifiedviews.plugins.extractor.sparqlendpoint.RemoteRdfDataUnit.execute(RemoteRdfDataUnit.java:130)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.executeAddons(AbstractDpu.java:230)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:162)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:248)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:386)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:468)
at java.lang.Thread.run(Thread.java:722)
```

Strange thing is that such no class definition is not thrown already when the dpu template e-sparqlEndpoint is loaded to UV. 

Appears for e-sparqlEndpoitn v 1.1.0. and also v 1.0.2, did not tested older versions

**Comment by eea03** [comment] 2015-11-23 10:44
I could not reproduce this on latest UV Core develop 2.2.x and e-sparqlEndpoint 1.1.0

From the stack trace it seems you don't have httpclient-osgi-4.3.3.jar in UV provided libs directory

**Comment by tomas-knap** [comment] 2015-11-23 11:11
Yes, this library is there, but still it is not working. @eea03 could you please put here the list of libraries in your target/lib?

**Comment by eea03** [comment] 2015-11-23 12:15
My target/lib:
```
commons-lang3-3.4.jar
httpclient-osgi-4.3.3.jar
httpcore-osgi-4.3.2.jar
jackson-annotations-2.4.4.jar
jackson-core-2.4.4.jar
jackson-databind-2.4.4.jar
jena-osgi-2.13.0.jar
jsonld-java-0.5.1.jar
libthrift-0.9.2.jar
org.apache.poi-bundle-3.10.0.jar
org.apache.servicemix.bundles.commons-csv-1.0-r706900_3.jar
org.apache.servicemix.bundles.jsch-0.1.49_1.jar
org.junit-bundle-4.11.0.jar
org.osgi.compendium-4.3.1.jar
```

**Comment by eea03** [comment] 2015-11-24 18:07
Any progress?
Would like to close this issue somehow because we need UV_Plugins v2.2.1 release ASAP so we can finalize our delivery packages and this is the last open issue planned for this release

Btw. I also tested it on our eDemo test environment (Core 2.2.x develop, DPU v 1.1.0) and could not reproduce this issue, it worked ok.

So i would expect there is some problem with your installation

**Comment by tomas-knap** [comment] 2015-11-26 09:36
Yes, probably. I would like to close this by tomorrow. But mostly likely the problem is at my site.

**Comment by tomas-knap** [comment] 2015-12-11 15:52
I was able to reproduce on a fresh Debian install of UV 2.3.0 (release branch). So the problem is there.

**Comment by tomas-knap** [comment] 2015-12-11 16:02
```Execution failed due to error: org/apache/http/pool/ConnPoolControljava.lang.NoClassDefFoundError: org/apache/http/pool/ConnPoolControl
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
at org.apache.http.impl.client.SystemDefaultHttpClient.createClientConnectionManager(SystemDefaultHttpClient.java:121)
at org.apache.http.impl.client.AbstractHttpClient.getConnectionManager(AbstractHttpClient.java:484)
at org.apache.http.impl.client.AbstractHttpClient.close(AbstractHttpClient.java:1011)
at org.apache.http.client.utils.HttpClientUtils.closeQuietly(HttpClientUtils.java:142)
at org.openrdf.http.client.SesameClientImpl.shutDown(SesameClientImpl.java:92)
at org.openrdf.repository.sparql.SPARQLRepository.shutDownInternal(SPARQLRepository.java:182)
at org.openrdf.repository.base.RepositoryBase.shutDown(RepositoryBase.java:52)
at eu.unifiedviews.plugins.extractor.sparqlendpoint.RemoteRdfDataUnit.close(RemoteRdfDataUnit.java:107)
at eu.unifiedviews.plugins.extractor.sparqlendpoint.RemoteRdfDataUnit.execute(RemoteRdfDataUnit.java:130)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.executeAddons(AbstractDpu.java:230)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:162)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:248)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:386)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:468)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.http.pool.ConnPoolControl
at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
... 27 more```

**Comment by tomas-knap** [comment] 2015-12-11 18:12
@eea03  Can you please send me content of your /Core/backend/target/lib folder? (lib folder which is a subfolder of the folder where backend.jar is)

**Comment by tomas-knap** [comment] 2015-12-11 18:18
The problem is that as the libraries for backend are prepared, the outdated version of httpcore is used - 4.0.1 ( because another library -  doxia-core - requires such version). At the same time, sesame started from some version using classes from httpcore 4.2+ (https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/pool/ConnPoolControl.html) - in particular it is used as RemoteRDFDataUnit is being closed in e-sparqlEndpoint.

**Comment by tomas-knap** [comment] 2015-12-15 08:15
Note: The fix was done by adjusting backend/pom.xml - which was done for version UV 2.3.0

**Closed** 2015-12-15 08:14 UTC
Labels: priority: High, severity: bug
