### ISSUE TITLE
SPARQL syntax validation for t-sparql* DPUs

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#207] opened 2015-04-28 13:25 UTC
When I'm developing a pipeline that uses some of the t-sparql* DPUs, I keep switching to SPARQL [query](http://sparql.org/query-validator.html) and [update](http://sparql.org/update-validator.html) validators to check if my query or update operation is syntactically valid. It would be useful to be able to validate the syntax of SPARQL directly in the t-sparql* DPUs. This can be either a button that would validate on user's demand or a validation that would be automatically triggered on change of the SPARQL input field.

**Comment by tomas-knap** [comment] 2015-04-30 09:16
From the usability point of view, this is important, increasing priority. The previous version - t-sparql - had such validation. SO these DPUs should be extended to also validate the query.

**Comment by pgo-eea-sk** [comment] 2015-06-18 12:26
There is some project setup problem with uv-t-sparqlSelect (missing import opencsv). It was there before I touched the code.

Another frontend issue is that there is different behaviour in menus Pipelines and DPU Templates. In menu DPU Templates, when I try to save invalid query, after pressing Save button Error message is issued, but TextArea with the query is reinicialized to last valid query. For example if I miss some character but make many changes in query, all changes will be lost. In Pipelines menu is it working correctly. After pressing Save, error message is issued but invalid query stays untouched, so I have chance to correct it.

**Comment by tomas-knap** [comment] 2015-06-24 09:20
missing import opencsv -> this could be caused by switching from sesame 2.7 -> 2.8. 

It should work in both cases in the way that it validates the query, but it does not deletes the invalid query. So the behavior of validation in DPU templates has to be adjusted

**Comment by mkl-eea-sk** [comment] 2015-06-24 09:27
this is bug in UV/frontend (replacing configuration each you save, even if invalid). create bug there. it has to be solved there (impossible to solve from dpu).

**Comment by skrchnavy** [comment] 2015-06-26 12:58
when #433 closed this can be also closed

**Comment by mkl-eea-sk** [comment] 2015-06-29 08:02
@skrchnavy what is #433 ?

**Comment by skrchnavy** [comment] 2015-06-29 11:58
Based on discussion with @mkl-eea-sk second comment https://github.com/UnifiedViews/Plugins/issues/207#issuecomment-113137149 is out of scope of this issue (is reported as UnifiedViews/Core#433).

So this issue can be closed when #246 closed.

**Closed** 2015-06-29 13:29 UTC
Labels: priority: High, resolution: fixed, severity: enhancement, status: resolved
