### ISSUE TITLE
t-zipper: Executing tests failed (master branch)

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#141] opened 2015-03-09 13:47 UTC
in master branch (03de59b3850cab20d103c569a67581099eef43e6), there was a problem with jenkins build - t-zipper DPU - tests for t-zipper failed, see below:

http://ci.in.eea.sk/view/OpenData.sk/job/UnifiedViews-Plugins%20%28master%29/12/console

[INFO] ------------------------------------------------------------------------
[INFO] Building T-Zipper 1.6.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ uv-t-zipper ---
[INFO] Deleting /home/jenkins/workspace/UnifiedViews-Plugins (master)/t-zipper/target
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ uv-t-zipper ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ uv-t-zipper ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /home/jenkins/workspace/UnifiedViews-Plugins (master)/t-zipper/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ uv-t-zipper ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ uv-t-zipper ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/jenkins/workspace/UnifiedViews-Plugins (master)/t-zipper/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ uv-t-zipper ---
[INFO] Surefire report directory: /home/jenkins/workspace/UnifiedViews-Plugins (master)/t-zipper/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running eu.unifiedviews.plugins.transformer.zipper.ZipperTest
13:55:29.072 [main] INFO  c.c.m.x.o.dpu.test.TestEnvironment - Creating cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment with workingDirectory /tmp/6228420703109304649
13:55:29.110 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Initializing NativeStore...
13:55:29.122 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Data dir is /tmp/6228420703109304649/dataUnits/test_env_9812134
13:55:29.163 [main] DEBUG o.openrdf.sail.nativerdf.TripleStore - No indexes specified, using default indexes: spoc,posc
13:55:29.182 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - NativeStore initialized
13:55:29.282 [main] INFO  c.c.m.x.o.c.a.d.r.l.LocalRDFDataUnit - Initialized Local RDF DataUnit named 'input' with data graph <http://linked.opendata.cz/resource/odcs/internal/pipeline/dpu-test/1/input>.
13:55:29.289 [main] INFO  c.c.m.x.o.c.a.d.r.l.LocalRDFDataUnit - Initialized Local RDF DataUnit named 'output' with data graph <http://linked.opendata.cz/resource/odcs/internal/pipeline/dpu-test/3/output>.
java.io.FileNotFoundException: /home/jenkins/workspace/UnifiedViews-Plugins%20(master)/t-zipper/target/test-classes/fileToZip.txt (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at eu.unifiedviews.plugins.transformer.zipper.ZipperTest.readFile(ZipperTest.java:115)
	at eu.unifiedviews.plugins.transformer.zipper.ZipperTest.validZipPasses(ZipperTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:294)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:127)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:207)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:146)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:106)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
13:55:29.426 [main] DEBUG o.o.query.parser.QueryParserRegistry - Registered service class org.openrdf.query.parser.serql.SeRQLParserFactory
13:55:29.453 [main] DEBUG o.o.query.parser.QueryParserRegistry - Registered service class org.openrdf.query.parser.sparql.SPARQLParserFactory
13:55:29.848 [main] INFO  e.u.h.d.dataset.DatasetBuilder - DatasetBuilder.build: <file:/tmp/6228420703109304649/dataUnits/test_env_98121343383212982338814287/>
13:55:29.848 [main] INFO  e.u.h.d.dataset.DatasetBuilder - 	remove:
13:55:29.848 [main] INFO  e.u.h.d.dataset.DatasetBuilder - 		file:/tmp/6228420703109304649/dataUnits/test_env_98121343383212982338814287/
13:55:29.848 [main] INFO  e.u.h.d.dataset.DatasetBuilder - 	default:
13:55:29.848 [main] INFO  e.u.h.d.dataset.DatasetBuilder - 	named:
13:55:29.950 [main] DEBUG e.u.p.transformer.zipper.Zipper - Adding file: fileToZip.txt
13:55:29.953 [main] INFO  e.u.h.d.dataset.DatasetBuilder - DatasetBuilder.build: <null>
13:55:29.953 [main] INFO  e.u.h.d.dataset.DatasetBuilder - 	remove:
13:55:29.953 [main] INFO  e.u.h.d.dataset.DatasetBuilder - 	default:
13:55:29.953 [main] INFO  e.u.h.d.dataset.DatasetBuilder - 		file:/tmp/6228420703109304649/dataUnits/test_env_9812134457822782495387986/
13:55:29.954 [main] INFO  e.u.h.d.dataset.DatasetBuilder - 	named:
13:55:29.955 [main] WARN  e.u.p.transformer.zipper.Zipper - Not all input files use VirtualPath, symbolic name is used instead.
13:55:30.075 [main] INFO  c.c.m.x.o.dpu.test.TestEnvironment - Creating cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment with workingDirectory /tmp/7755908000868581128
13:55:30.076 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Initializing NativeStore...
13:55:30.077 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Data dir is /tmp/7755908000868581128/dataUnits/test_env_30833048
13:55:30.080 [main] DEBUG o.openrdf.sail.nativerdf.TripleStore - No indexes specified, using default indexes: spoc,posc
13:55:30.081 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - NativeStore initialized
13:55:30.081 [main] INFO  c.c.m.x.o.c.a.d.r.l.LocalRDFDataUnit - Initialized Local RDF DataUnit named 'input' with data graph <http://linked.opendata.cz/resource/odcs/internal/pipeline/dpu-test/1/input>.
13:55:30.082 [main] INFO  c.c.m.x.o.c.a.d.r.l.LocalRDFDataUnit - Initialized Local RDF DataUnit named 'output' with data graph <http://linked.opendata.cz/resource/odcs/internal/pipeline/dpu-test/3/output>.
13:55:30.361 [main] ERROR c.c.m.x.o.d.test.context.TestContext - DPU publish message short: 'DPU Failed' long: 'Cant get file iterator'
eu.unifiedviews.dataunit.DataUnitException: 
	at org.powermock.api.mockito.internal.invocation.MockitoMethodInvocationControl.performIntercept(MockitoMethodInvocationControl.java:260) ~[na:na]
	at org.powermock.api.mockito.internal.invocation.MockitoMethodInvocationControl.invoke(MockitoMethodInvocationControl.java:192) ~[na:na]
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:124) ~[powermock-core-1.6.1.jar:na]
	at org.powermock.core.MockGateway.methodCall(MockGateway.java:63) ~[powermock-core-1.6.1.jar:na]
	at eu.unifiedviews.helpers.dataunit.fileshelper.FilesHelper.getFiles(FilesHelper.java) ~[na:na]
	at eu.unifiedviews.plugins.transformer.zipper.Zipper.execute(Zipper.java:71) ~[na:na]
	at cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment.run(TestEnvironment.java:311) [na:na]
	at eu.unifiedviews.plugins.transformer.zipper.ZipperTest.dataUnitIteratorFails(ZipperTest.java:85) [na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_76]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_76]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_76]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_76]
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68) [junit-4.12.jar:4.12]
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:310) [na:na]
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97) [junit-4.12.jar:4.12]
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:294) [na:na]
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:127) [na:na]
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82) [na:na]
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282) [na:na]
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50) [junit-4.12.jar:4.12]
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:207) [na:na]
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:146) [na:na]
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:120) [na:na]
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44) [junit-4.12.jar:4.12]
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:122) [na:na]
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:106) [powermock-module-junit4-common-1.6.1.jar:na]
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53) [powermock-module-junit4-common-1.6.1.jar:na]
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59) [powermock-module-junit4-1.6.1.jar:na]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264) [surefire-junit4-2.17.jar:2.17]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.17.jar:2.17]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124) [surefire-junit4-2.17.jar:2.17]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200) [surefire-booter-2.17.jar:2.17]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153) [surefire-booter-2.17.jar:2.17]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.17.jar:2.17]
13:55:30.376 [main] INFO  c.c.m.x.o.dpu.test.TestEnvironment - Creating cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment with workingDirectory /tmp/8483091598515494068
13:55:30.377 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Initializing NativeStore...
13:55:30.377 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Data dir is /tmp/8483091598515494068/dataUnits/test_env_31436411
13:55:30.380 [main] DEBUG o.openrdf.sail.nativerdf.TripleStore - No indexes specified, using default indexes: spoc,posc
13:55:30.381 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - NativeStore initialized
13:55:30.382 [main] INFO  c.c.m.x.o.c.a.d.r.l.LocalRDFDataUnit - Initialized Local RDF DataUnit named 'input' with data graph <http://linked.opendata.cz/resource/odcs/internal/pipeline/dpu-test/1/input>.
13:55:30.382 [main] INFO  c.c.m.x.o.c.a.d.r.l.LocalRDFDataUnit - Initialized Local RDF DataUnit named 'output' with data graph <http://linked.opendata.cz/resource/odcs/internal/pipeline/dpu-test/3/output>.
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.892 sec <<< FAILURE! - in eu.unifiedviews.plugins.transformer.zipper.ZipperTest
validZipPasses(eu.unifiedviews.plugins.transformer.zipper.ZipperTest)  Time elapsed: 1.761 sec  <<< FAILURE!
java.lang.AssertionError: Content of file before and after zipping should match! expected:<null> but was:<Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam accumsan enim mi, ut lacinia mi vulputate vitae. Nulla id consequat nulla. Nam a auctor nisl. Sed eleifend felis in sapien tincidunt, eu vestibulum sapien posuere. Donec turpis nisl, accumsan vitae placerat eget, ornare pretium purus. Nulla purus est, molestie vel nunc mattis, pharetra iaculis velit. Quisque mattis feugiat lorem eget dignissim.>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at eu.unifiedviews.plugins.transformer.zipper.ZipperTest.validZipPasses(ZipperTest.java:77)

Results :

Failed tests: 
  ZipperTest.validZipPasses:77 Content of file before and after zipping should match! expected:<null> but was:<Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam accumsan enim mi, ut lacinia mi vulputate vitae. Nulla id consequat nulla. Nam a auctor nisl. Sed eleifend felis in sapien tincidunt, eu vestibulum sapien posuere. Donec turpis nisl, accumsan vitae placerat eget, ornare pretium purus. Nulla purus est, molestie vel nunc mattis, pharetra iaculis velit. Quisque mattis feugiat lorem eget dignissim.>

Tests run: 3, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] E-FilesFromLocal .................................. SUCCESS [4.454s]
[INFO] E-RdfFromSparqlEndpoint ........................... SUCCESS [5.665s]
[INFO] E-HttpDownload .................................... SUCCESS [1.734s]
[INFO] E-UploadToFiles ................................... SUCCESS [1.754s]
[INFO] T-SPARQL .......................................... SUCCESS [4.527s]
[INFO] T-SPARQLSelect .................................... SUCCESS [1.659s]
[INFO] T-XSLT ............................................ SUCCESS [6.082s]
[INFO] T-FilesRenamer .................................... SUCCESS [2.215s]
[INFO] T-FilesFilter ..................................... SUCCESS [1.448s]
[INFO] T-FilesToRdf ...................................... SUCCESS [1.609s]
[INFO] T-RdfToFiles ...................................... SUCCESS [1.515s]
[INFO] T-Zipper .......................................... FAILURE [3.616s]
[INFO] T-UnZipper ........................................ SKIPPED

**Comment by skrchnavy** [comment] 2015-03-09 22:22
T-ZIPPER has broken tests from version 1.5.5 version of Plugins - that is from 10.2.2015.

**Comment by skrchnavy** [comment] 2015-03-09 22:37
root cause: java.io.FileNotFoundException: /home/jenkins/workspace/UnifiedViews-Plugins%20(master)/t-zipper/target/test-classes/fileToZip.txt (No such file or directory)
@eea02  to fix the test

**Comment by eea02** [comment] 2015-03-19 10:48
Unit test was fixed in commit f80b4241a420d70520488ec5e22674dce5f7215c. Merging it from develop will fix the issue.

**Comment by skrchnavy** [comment] 2015-03-19 11:26
This has to be cherrypicked or reimplemented again in develop, there was very pessimistic merge after the release 1.6 due to huge refactoring of DPUs in develop.

**Comment by tomas-knap** [comment] 2015-03-26 12:30
Please replay/cherry pick the commit https://github.com/UnifiedViews/Plugins/commit/f80b4241a420d70520488ec5e22674dce5f7215c 
to develop

**Comment by skrchnavy** [comment] 2015-03-26 14:57
@eea02 to fix this if not yet done

**Closed** 2015-03-29 15:52 UTC
Labels: priority: High, resolution: fixed, severity: bug, status: resolved
