### ISSUE TITLE
t-relationalToRdf : last row of relational table is always skipped

### ISSUE THREAD

**Issue by loryzizu** [UnifiedViews/Plugins#395] opened 2016-10-05 10:49 UTC
There is an error when DPU iterates over row. The last row of query result set is not parsed.

**Comment by tomas-knap** [comment] 2016-10-06 07:38
Thanks for pointing that out! We will check and correct.

**Comment by tomas-knap** [comment] 2016-10-07 12:13
related to https://github.com/UnifiedViews/Plugins/issues/378?

**Comment by tomas-knap** [comment] 2016-10-07 12:14
Please can you provide some more information to the inputs on which it fails?

**Comment by hanecak** [comment] 2016-10-07 12:17
@tomas-knap , yes, this looks as duplicate of #378 . Thus yes, we would like to see the pipeline and source data, if possible.

**Comment by loryzizu** [comment] 2016-10-11 09:24
Sorry for the delay. Yes, it looks as duplicate of #378.

Unfortunately now we can't provide publicly the pipeline and source data. 

Anyway we have relationalFromSql-2.1.3 with a simple query (only one table, no join) from Oracle db, linked to relationalToCkan and relationalToRdf. 
The CSV file returned from relationalToCkan has all the source's row, the RDF returned from relationalToRdf has all the rows minus the last one.

**Comment by tomas-knap** [comment] 2016-10-17 10:27
Solved by https://github.com/UnifiedViews/Plugins/pull/398

**Closed by tomas-knap** 2016-10-17 10:27 UTC
Labels: severity: bug
