### ISSUE TITLE
Align DPU: t-xslt

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#100] opened 2015-02-10 08:59 UTC
There are 2 versions of t-xslt

UnifiedViews/Plugins repo (this repo)
mff-uk/DPUs repository (in non-published branch)

One version is enough so we should migrate to one DPU. First task is to propose how the DPUs should be aligned - either we may use one DPU or we may merge the features from both DPUs.

**Comment by mkl-eea-sk** [comment] 2015-02-10 09:56
publish branch here please https://github.com/mff-uk/DPUs

**Comment by skrchnavy** [comment] 2015-02-13 09:01
available in brach feature/2.0.0: https://github.com/mff-uk/DPUs/tree/feature/2.0.0/dpu/t-xslt

**Comment by skrchnavy** [comment] 2015-02-13 09:31
version of https://github.com/UnifiedViews/Plugins/blob/master/t-xslt/README.md is also outdated, shall be updated according to changes during merge. Also version history shall be corrected

**Comment by mkl-eea-sk** [comment] 2015-02-13 10:00
master branch?

**Comment by jindrichmynarz** [comment] 2015-02-19 13:10
Upon request from @tomas-knap, here's a brief comparison of the XSLT DPUs from a user's perspective concerning only the differences in user interface.

I compared these 2 DPUs:

1. t-xslt DPU from this repository: <https://github.com/UnifiedViews/Plugins/tree/develop/t-xslt>
2. t-xslt DPU from <https://github.com/mff-uk/DPUs> repository. Since the version at <https://github.com/mff-uk/DPUs/tree/feature/2.0.0/dpu/t-xslt> cannot be compiled, I used a JAR-file provided by @skodape (in case it is needed, I hope he can fill in exact commit the JAR was produced from).

Both DPUs provide these parameters:

- Output file extension (text input)
- Skip file on error (checkbox)
- XSLT template (text input)

DPU 1 also allows to upload XSLT from a file.

DPU 2 provides these additional parameters:

- Number of extra threads (text input)
- Enable fault tolerance (checkbox)
  - Unlike others, this option is not documented in the "About" tab.

It can also load its config from another DPU.

DPU 1 works, but it is slow. Transformation of 1256 files (9.4 MB) takes 11 minutes. Transformation of the same dataset using the same version of Saxon (9.4) on the same machine with the same maximum heap size takes ~14 seconds on single thread (performance actually degrades when more threads are used, probably due to the coordination overhead).

I couldn't test much the functionality of DPU 2 due to exceptions. I wanted to test the speedup gained from using multiple threads, but when I passed it multiple files via E-FilesFromLocal, it raised the following exception:

`Failed to configure DPU.
stack trace:java.io.PrintWriter@48cf1fb8`

**Comment by skodape** [comment] 2015-02-21 18:14
@jindrichmynarz Unfortunately I can't provide commit number as I do not know (it's some migration mid version, probably).
But I would like to see the pipeline so I can find the source of this exception and fix it, so you can finish the comparison.

**Comment by tomas-knap** [comment] 2015-02-22 09:32
Thanks, @skodape, please help Jindrich to fix the issue, so that we can finish the comparison next week.

**Comment by jindrichmynarz** [comment] 2015-02-23 08:19
I managed to get DPU 2 working. For the same payload it takes ~13 seconds to transform, which is an order of magnitude faster than DPU 1. Skipping files on error works almost as expected. Processing a file with error raises an exception (note that the error message contains a typo "Error processig file number"; should read "processing"), however, the pipeline keeps running instead of being marked as failed and cancelling it doesn't work. The back-end throws this exception:

```
2015-02-23 08:54:41,734 [dpu: t-uk-xslt] INFO  exec:22 dpu:5 c.c.m.x.u.t.xslt.Xslt - InterruptedException
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2017) ~[na:1.7.0_25]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2095) ~[na:1.7.0_25]
	at java.util.concurrent.ArrayBlockingQueue.offer(ArrayBlockingQueue.java:350) ~[na:1.7.0_25]
	at cz.cuni.mff.xrg.uv.transformer.xslt.Xslt.innerExecute(Xslt.java:123) ~[na:na]
	at cz.cuni.mff.xrg.uv.boost.dpu.advanced.AbstractDpu.execute(AbstractDpu.java:126) ~[na:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232) ~[backend-1.6.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370) ~[backend-1.6.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452) ~[backend-1.6.0-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
```

**Comment by skodape** [comment] 2015-02-23 13:34
@jindrichmynarz Thank for info. I think I know where the problem is and I try to fix it asap and let you know here - so you re-test and make sure that it works as expected.

**Comment by jindrichmynarz** [comment] 2015-02-24 10:15
So, from my perspective as a DPU user, [DPU 2](https://github.com/mff-uk/DPUs/tree/feature/2.0.0/dpu/t-xslt) should be adopted, because it has more options and is faster. Now someone else (@tomas-knap?) should review the DPUs from the standpoint of code quality.

**Comment by tomas-knap** [comment] 2015-02-24 19:51
Ok, mff-uk/DPU version will be used

**Comment by jindrichmynarz** [comment] 2015-03-11 15:27
@skrchnavy, @tomas-knap, can we prioritize this issue? Many pipelines to be made depend on t-xslt. Moreover, the issue #128 that depends on this one is a blocking the pipeline for the Slovak National Library.

However, the latest version (4d2b96af49564ecdf58345cfd927fde7f0e85661) of this DPU doesn't compile (plus its tests fail, #140) and [t-uk-xslt](https://github.com/mff-uk/DPUs/tree/feature/2.0.0/dpu/t-xslt) doesn't work in recent builds of UnifiedViews/Core.

**Comment by tomas-knap** [comment] 2015-03-13 11:01
The develop branch should already contained aligned t-xslt DPU. 

@skodape, could you please check #140?

**Comment by hanecak** [comment] 2015-03-26 09:37
Current status:
1. Jenkins is currently able to build t-xlst (see http://ci.in.eea.sk/view/OpenData.sk/job/UnifiedViews-Plugins%20%28develop%29/63/console)
2. #140 is closed

@tomas-knap, I think, this can be closed.

**Closed** 2015-03-26 10:02 UTC
Labels: priority: High, severity: enhancement
